language: cpp
dist: xenial

git:
  depth: 10

matrix:
  include:
  - os: linux
    compiler: gcc           # g++-5, Qt5.12.0, IPC enabled
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
        packages: [ g++-5 qt512base qt512declarative ]
    env: COMPILER=g++-5 QT=512 DISABLE_IPC=OFF
  - os: linux
    compiler: gcc           # g++-5, Qt5.12.0, IPC disabled
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
        packages: [ g++-5 qt512base qt512declarative ]
    env: COMPILER=g++-5 QT=512 DISABLE_IPC=ON
  - os: linux
    compiler: clang          # clang-6.0, Qt5.12.0, IPC enabled
    addons:
      apt:
        sources:
        - ubuntu-toolchain-r-test
        - sourceline: 'ppa:beineri/opt-qt-5.12.0-xenial'
        packages: [ clang-6.0 libstdc++-6-dev qt512base qt512declarative ]
    env: COMPILER=clang++-6.0 QT=512 DISABLE_IPC=OFF

  # TODO: all combined-inprocess-async-... tests fail, if IPC is disabled. The interface never becomes ready.
  allow_failures:
  - env: COMPILER=g++-5 QT=512 DISABLE_IPC=ON

install:
- sudo apt-get install python3 python3-pip python3-setuptools doxygen libgl1-mesa-dev
- sudo pip3 install antlr4-python3-runtime six pyyaml click typing jinja2 watchdog path.py

before_script:
- QTDIR="/opt/qt${QT}"
- PATH="$QTDIR/bin:$PATH"
- source /opt/qt${QT}/bin/qt${QT}-env.sh
- cd ${TRAVIS_BUILD_DIR}
- mkdir build
- source setup_gtest.sh

script:
- cd build
- >
  cmake -DCMAKE_CXX_COMPILER=${COMPILER} -DCMAKE_BUILD_TYPE=Release -DFACELIFT_DISABLE_DBUS_IPC=${DISABLE_IPC} -DFACELIFT_BUILD_TESTS=ON -DCMAKE_SYSTEM_PREFIX_PATH=$CMAKE_SYSTEM_PREFIX_PATH ..
- make -j2 && dbus-launch make check && cat ./tests/results.csv
