/**********************************************************************
**
** Copyright (C) Luxoft Sweden AB 2020
**
** This file is part of the documentation of the FaceLift project
**
** This work is licensed under the Creative Commons
** Attribution-ShareAlike 4.0 International License. To view a copy of
** this license, visit http://creativecommons.org/licenses/by-sa/4.0/
** or send a letter to Creative Commons, PO Box 1866, Mountain View,
** CA 94042, USA.
**
** SPDX-License-Identifier: CC-BY-SA-4.0
**
**********************************************************************/

/**
\page page-generated Generated code structure

This page refers to the code generated by Addressbook example located in examples/AddressBook. The purpose is to
provide an outline of generated code structure.

The diagram below shows the overall structure of the generated code and its relation to the non-generated classes.

\startuml

class QObjectWrapperPointerBase
class "QObjectWrapperPointer<StructQMLWrapperType>" as QObjectWrapperPointer_t << (T, #00DDAA) template>>

QObjectWrapperPointerBase <|-- QObjectWrapperPointer_t

class "facelift::InterfaceBase" as InterfaceBase {
}
abstract class AddressBook
class AddressBookImplementationBase

class AddressBookQMLAdapter
class "facelift::Property<Type>" as Property << (T, #00DDAA) template>>
class "facelift::ServiceProperty<Type>" as ServiceProperty << (T, #00DDAA) template>>
class "facelift::ListProperty<Type>" as ListProperty << (T, #00DDAA) template>>
class AddressBookQMLImplementationProvider
class QMLModelImplementationFrontendBase {
#{static} s_engine : QQmlEngine*
}
class "facelift::QMLModelImplementationFrontend<QMLModelImplementationType>" as QMLModelImplementationFrontend << (T, #00DDAA) template>>
class AddressBookImplementationBaseQML
class "facelift::ModelQMLImplementation<InterfaceType>" as ModelQMLImplementation_t << (T, #00DDAA) template>>

InterfaceBase <|-- AddressBook
AddressBook o-- AddressBookQMLAdapter
AddressBook <|-- AddressBookImplementationBase
AddressBook "1" *-- "n" Property
AddressBook "1" *-- "n" ListProperty
AddressBook "1" o-- "n" ServiceProperty

AddressBookImplementationBase <|-down- AddressBookQMLImplementationProvider

QMLModelImplementationFrontend <|-right- AddressBookQMLImplementationProvider
QMLModelImplementationFrontendBase <|-up- QMLModelImplementationFrontend
QMLModelImplementationFrontendBase "n" *-- "1" QQmlEngine : <<static; shared ownership;\ncreates>>

ModelQMLImplementation_t <|-- AddressBookImplementationBaseQML
QObject <|-- ModelQMLImplementationBase

QQmlParserStatus <|-- ModelQMLImplementationBase
ModelQMLImplementationBase <|-- ModelQMLImplementation_t

ModelQMLImplementationBase o-- InterfaceBase
ModelQMLImplementationBase "1" *-right- "n" "QObject " : QML properties

ModelQMLImplementation_t o-- AddressBookQMLImplementationProvider : <<template parameter>>

AddressBookImplementationBaseQML --> AddressBookQMLImplementationProvider : <<creates>>
AddressBookImplementationBaseQML "1" *-up- "n" QObjectWrapperPointer_t : facelift structure\npointer wrapped

AddressBookQMLAdapter o-- AddressBook
AddressBookQMLAdapter <|-- QMLAdapterBase

\enduml

*/
